tk_models.py
This branch should be merged to add a template for the pages of the application, which will allow easy editing in the future.
The template is similar to a Frame from Tkinter's library, but with a few differences. There is the option to add a title and a back button, which navigates to a previous Frame. Also, this can be modified later to give it better styling.
=> Create template for application pages

ExperimentSetupFrame.py, NavigateButton.py, experSetupProto.py
What was changed?
The page was updated to better match the team's style. Variables were also updated to snake case for code consistency.
A navigation button class was also added as the code was being reused for multiple classes. Finally, the file name was changed.
Why was it changed?
The original file used Tkinter buttons rather than the newer ttk version and the team agreed upon snake case for our coding style going forward. File name change to match the style of the other app frame classes created.
How was it changed?
The NavigateButton used the newer UI reflecting the buttons.
Example screenshot:
Signed-off-by: Cori Diaz <102837772+coridiaz@users.noreply.github.com>
=> Experiment Setup Prototype Page

GroupOrganizationFrame.py
**What was Changed?**
- the frame for organizing the groups was added and fits in to navigation.
Demonstration:
=> adding group organization frame

ExperimentSetupFrame.py, MouserPage.py, authentication.py, grid_mouser_page.py, group_config_ui.py, main.py, new_exper_ui.py, new_experiment_frame.py, test_frame.py
**Purpose for Request**
progress on our new experiment setup pages, solved issue of check button bug
main.py was modified to reflect the new experiment page
new_exper_ui.py was created modeled after our updated prototype
group_config_ui.py was created as a template for navigation purposes
Screenshot of Page:
=> New Experiment UI / Check Button Issue Resolved

ExperimentDatabase.py
Added several functions to make the database usable. 
- setup_measurement_items
- update_group_and_cage
- deactivate_animal
Changed several functions to make them more useful
- get_animals
- add_animals
=> Database functionality

ExperimentDatabase.py
Fixed bug caused by missing comma
=> Fixed bug caused by missing comma

main.py
Signed-off-by: Cori Diaz <102837772+coridiaz@users.noreply.github.com>
=> fix filename in main.py

README.md, requirements.txt
Closes #62 
A requirements file was added, and the README file was edited to explain what needs to be installed.
It was changed because multiple people have attempted to run the application without knowing what libraries need to be installed, so the requirements file was added to make this process simpler.
I added the requirements file with a list of dependencies necessary for this project.
=> 62 add dependencies

login.py
An unused import line of code in login.py was removed.
**Why was this changed?**
The import file no longer exists and was therefore causing an error upon running the app.
=> removing unused import line

ExperimentDatabase.py
updated database to give dictionaries
=> Cage UI database

experiment_pages/summary_ui.py
**What Was Changed?**
Summary UI page formatting was updated 
**Why Was This Changed?**
The summary page for new experiment setup did not always format properly before.
It now clearly labels the data displayed and is spaced properly for better user experience.
**Screenshots:**
Closes #74
=> Summary UI fix

database_apis/.gitignore, database_apis/data_collection_database.py, database_apis/experiment_database.py, database_controller.py, experiment_pages/data_collection_ui.py, requirements.txt
Closes #77 
The data collection page was changed to fit the clients needs and connect it to the database
It was changed because the user needs to have an automated process for entering data, and the data needs to be saved for later use
I configured data_collection_ui.py, the UI, and data_collection_database.py, the database. I connected these two files by file reference, and I added a few UI changes with Tkinter's library.
=> Connect Data Collection Page to Database

database_apis/data_collection_database.py
The data collection page was modified to fix an error that was occurring when it was ran. This error was in relation to a directory/file not existing in the project.
It was changed because the user could not progress far into the application with this error.
I added a line within data_collection_database.py that created the error-specified directory if it did not exist.
=> Fix data collection error

README.md
Closes #90
The README file was changed to add a developer guide.
The developer guide was added so that future developers for this project can understand its structure easily.
I added multiple bullet points within the README file, including ones on machine requirements and file structure, by using the syntax for README files.
=> 90 developer guide

database_apis/experiment_database.py, database_controller.py, experiment_pages/cage_config_ui.py, experiment_pages/experiment_menu_ui.py, experiment_pages/map_rfid.py
**What was Changed:**
- Remove hardcoded values in cage_config_ui
- Merged overwritten code for move animals in cage_config_ui from a previous PR
- Fixed Simulate RFID numbering issue
**Why was this changed?**
- The previous cage_config_ui file had hardcoded values because the animals were not added into the db, now the page and database_controller pull the added animal data from the database and display it in the UI.
- Functionality for updating the page and error checking manually moving animals was overwritten in a previous pull request so that functionality was added back in with the saving to the database for auto sort.
- Map RFID page previously did not load back in animals that were already added when reopening the page.
closes #100 
closes #101
=> Merging Sort and Move for Cage Configuration

experiment_pages/new_experiment_ui.py
Fixes #105
add_investigator() now checks to see if the entry is empty before storing the string. If it is empty, it no longer stores the string.
=> Added check to add_investigator() to disallow empty strings

database_test.py
Fixes #134 
Added a new file called *database_test.py* which contains the automated testing for our database functions
Previously we had no unit testing in place, as such adding unit-testing was required in order to insure the functionality of the code.
The testing file uses a dummy databases to check the behaviors of the ExperimentDatabase functions.
16 unittests were created to test every function that returns a value in ExperimentDatabase class
=> Added database tests

experiment_pages/map_rfid.py
Fixes #124
After Deleting an entry, the animal ID now correlates to the correct number of entries. Before, if you deleted item number four, the next entry would be item five. Now it would display the next entry correctly as item number four.
I changed the map_rfid page to correlate to the animal_id.
It was changed because the prior delete method was not doing its job. If you had deleted an item for an experiment with 12 animals, it would only allow you to have 11 animals in the experiment. As the program added when the next number after deletion would read that the max number of animals was reached.
Added a method to find the correct value of the animal_id after removal.
=> Animal ID after Deletion

.gitignore, experiment_pages/experiment.py, experiment_pages/new_experiment_ui.py, experiment_pages/password_utils.py, experiment_pages/summary_ui.py, main.py, requirements.txt
Fixes #152 
1. Did the following changes to fix the issue - **"Any experiment files that are saved (when creating the experiment) or opened (from the menu bar) should be ".mouser" files, rather than ".db" files":**
a. In summary_ui.py -> save_to_database() - changed the file extension to .mouser instead of .db to save the created files as .mouser
b. In main.py -> open_file() - changes are done to populate the .mouser files to the user for file selection during open_file()
2. Did the following changes to fix the issue 
**"Passwords - Give users the option to set a password for their experiment:"**
a. In new_experiment_ui.py -> added the label Password next to the experiment name to provide an option to set a password for the experiment and sending to the setter method …
=> Changes for password protection and other configuration settings

experiment_pages/experiment/data_collection_ui.py
Fixes #167 
Added A scrollbar to data collection in case of large group sizes.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
Added the scrollbar logic that is used in other pages to the Data Collection page
Bunched up with larger group sizes that would exceed the size of the frame, allows users to see all animals in large group size.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
#167
No code was changed only added. Added the lines needed for CTkCanvas and scrollbar.
**Screenshots that show the changes (if applicable):**
=> Scroll Bar Data Collection

databases/experiment_database.py, experiment_pages/create_experiment/new_experiment_ui.py, experiment_pages/experiment/cage_config_ui.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/experiment_menu_ui.py, experiment_pages/experiment/group_config_ui.py, main.py, shared/experiment.py
Fixes #162 
Any methods and classes that touch data collection are changed to work with the new table in the database.
Added a new table into the experiment_database file that's meant to store the collected data. Making a new experiment fully sets up this table to include all measurement items.
Data Collection UI now uses the data found in the database file for retrieving and writing data
New table is created in the constructor of ExperimentDatabase called collected_data. This table starts with two columns, date and animal_id. Before this is can be used to collect data, the function setup_collected_data which takes a list of measurement items and creates a new column in the *collected_data* table for each measurement …
=> Move data collection to the .mouser file

main.py
Fixes #200 
In menu bar, I added clearer option descriptions under "File"
To make the options clear in their functionality
Modified line118-120 in main.py
=> Added clearer options according to #200

databases/experiment_database.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/map_rfid.py, main.py, shared/password_utils.py, shared/tk_models.py
Fixes #185 
Fixes #186 
Anywhere that calls AudioManager.play() had the file path of the audio file being played changed. Experiment database now has a function to changed the RFID number of an animal.
Fixed additional errors in map_rfid that were caused when removing and adding animals.
Audio was not working anywhere in the program.
There is an error when removing then adding an RFID in the map_rfid function
- Removing all animals at once resulted in the added animal_id being to large
- Added animals after the maximum number of animals was reached (even after removing an animal) led to an error where all cages and groups were full.
Everywhere in the program that calls AudioManager.play() now plays from the directory …
=> Fixing sound error and errors in map rfid

experiment_pages/experiment/experiment_menu_ui.py, experiment_pages/experiment/map_rfid.py, shared/tk_models.py
Fixes #192 
Added a function called all_rfid_mapped() which returns true if the number of mapped rfids is equal to the total number of animals in the experiment.
Added function called on_show_frame() that checks to see if all_rfid_mapped is true and enables/disables group_configuration, collection, and data_analysis accordingly.
Overrode raise_frame function for experiment_menu button. Now also calls on_show_frame.
Changed  MenuButton and ChangePageButton so that they take MouserPages and the navigate functions of them to use the function MouserPage.raise_frame(). 
https://github.com/oss-slu/Mouser/blob/5d886c02bae1f1ca0b16b883921b34213a1782e4/shared/tk_models.py#L114-L146
Also changed the function press_back_to_menu_button() in map_rfid so that it calls navigate …
=> Added new function to check if all the animals are mapped

experiment_pages/experiment/map_rfid.py
#204
Fixes #204 
Change RFID, Table Height, Remove Selections.
Enhances the functionality of mapping the RFID.
Change the functions directly
**Screenshots that show the changes (if applicable):**
=> MapRFID Changes

.github/workflows/Pylint.yaml, experiment_pages/create_experiment/new_experiment_ui.py, requirements.txt
fixes #169
Changes are to new_experiment_ui.py, the file responsible for the ui when users are first creating a new experiment. 
As well as fixing issue#169, these changes also fix a bug. Previously the event handler code was incorrectly implemented and the program checked required fields only when the investigators or measurement fields were edited. Now, the program checks required fields with the previous event handler. I also removed a duplicate method that defined which required fields to check before enabling the next button.
Changed configuration parameter when button is created.
Added code in __init__ to properly handle binding entry widgets.
*Issue #169 mentions raising a warning when users click 'next' with …
=> Fixes #169

README.md
Fixes #157 
The README file was changed to address the tasks in issue #157 
- Description now matches Mouser portfolio page
- Installing requirements section now uses the correct requirements.txt syntax
- File structure section better reflects current version
- Added Local Dev Setup and Contribution sections to improve Developer Guide
=> Improve README, fixes#157

experiment_pages/experiment/experiment_menu_ui.py
Reversing merge to isolate origin of Pylint workflow error.
=> Revert "Fix for bug #214"

databases/experiment_database.py, experiment_pages/experiment/data_analysis_ui.py, experiment_pages/experiment/experiment_menu_ui.py
This update corrects what the functionality of what the former "Data Analysis" button was intended for. It will renamed to "Data Exporting" and is reflected in the actual page as well. This update also creates the functionality to export files into a new "exports" folder within the Mouser folder. Each export goes into a folder sharing the name of the experiment. 
Fixes #224 
The experiment menu page button and the data analysis page itself have been renamed to Data Generation. In addition, it now takes the currently opened experiment and, with the push of a button, exports all tables into .csv file format, inserting those files into a folder sharing the experiment name inside of a new "exports" folder. 
This is to better align with client …
=> Updates to experiment menu and data analysis pages

main.py
Super quick change to the password box.
=> UI changes – added bigger border to Password box

.github/workflows/create-executable.yml, databases/experiment_database.py, experiment_pages/experiment/data_analysis_ui.py
Fixes #224 
Comments were left on the other branch implementing fixes for issue #224 that are addressed here. Now, the user can select a folder location the same as if they were saving a file during experiment creation before exporting all saved data to .csv format.
This was changed as there were concerns moving forward about having the project save files to an internal folder that may not exist when the .exe changes are complete. This allows for portability with the data after it is no longer being launched from the command line. 
The user is prompted within the data_analysis_ui.py file to select where they would like the exported data to be saved. Inside the experiment_database.py file the export_data_to_csv method …
=> Followup Enchancements to #224

databases/experiment_database.py, experiment_pages/experiment/data_analysis_ui.py
Fixes #250 
A change to the data export feature is currently being worked on to change the output of the files from 7 .csv files down to two files.
This is being changed to be more user friendly as currently there are seven files outputted with a bunch of either not useful information or duplicate and overlapping information. 
data_analysis_ui.py has been updated to change the method being called when the export button is pressed. Now, instead of export to csv, it will call a method export to single csv method. That method is defined inside of the experiment_database.py file, which has the new method defined inside of it.[COMPLETE] Now down to two files, one for data collected and the other to see what groups are sorted …
=> [COMPLETE] Enhanced Data Export Implementation

experiment_pages/experiment/data_analysis_ui.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/experiment_menu_ui.py
Fixes #246 
In data_analysis_ui.py, enlarged core UI elements. Buttons and labels were resized with larger fonts and improved spacing for better usability. A prominent title was added to the main frame. Notifications now use CTkToplevel for better user experience with larger size and clear feedback. Clear error messages for missing database files or export failures were added. In the experiment_menu_ui.py, increased button and label dimensions and font sizes. Resized and adjusted dialog boxes for clarity. Ensured proper scaling on various screen sizes. 
To ensure compatibility on devices with different screen sizes and increase size of UI in general to make the program more lab friendly.  To provide users with clear feedback and reduce errors. …
=> ui changes

.github/workflows/create-executable.yml, shared/serial_port_settings.py
Fixes Serial Issue for .exe file
Minor change to ensure OS compatibility when exporting to .exe.
This change ensures when non-dev environments run Mouser it works. 
Serial_settings.py has a few lines changed to match the OS settings that are used on modern systems, since the old way did not work outside of the dev environment.
=> Serial setting path for executable

databases/experiment_database.py, experiment_pages/experiment/review_ui.py
Fixes #283 
The ReviewUI page of the application was updated to display a full summary of experiment data. A new create_summary_frame() method was added to organize and show information such as experiment name, species, measurement items, group names, and RFID usage. Labels were dynamically created inside main_frame to present data pulled directly from the database.
Previously, the ReviewUI only showed placeholder text. This update addresses that by pulling stored data from the database, providing users with a clear and complete overview of their configured experiment. It helps ensure users can verify all experiment settings in one place before continuing.
The file review_ui.py was modified by instantiating a connection …
=> review page is working, will have slight tweaks to improve UI

databases/experiment_database.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/map_rfid.py
Fixes #299
In the process of overhauling the database, it created a bug that hindered the programs ability to measure an animal that they scan.
This is one of the most important features that is visible to the user, our client needs to scan the animal that he wishes to measure, without the scanning feature, Mouser isn't really usable.
Most of it boiled down to changing method names/ arguments for any database related functions. I also had to write a buffer that kills the thread upon scan due to an issue with reading a null scan immediately after an RFID scan.
=> Collection screen works with RFIDs again

experiment_pages/experiment/data_analysis_ui.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/map_rfid.py
Fixes #277 
Additional Success / Error sounds were added where appropriate.
Removed new window from being created on successful data export. Instead, a temporary success banner will now appear.
The correct audio feedback needs to be implemented throughout the app. The data export dialog box was removed as a small QoL fix.
=> Additional Sounds and Better Export Notification + Quick RFID Bug fixes

databases/experiment_database.py, experiment_pages/experiment/data_analysis_ui.py
Fixes #290 
Data exporting was changed to have column names specific to the client needs, as well as exporting to one .csv file.
The current "old" Mouser simply exports everything as a folder of different .csvs with different info (RFID, weights, IDs, etc.) which is very redundant, so this cleans it up.
Nothing crazy so far, just added column names to the data frame and exported them to a .csv.
=> Data re-formatting

main.py, requirements.txt
=> Fixing UI Graphics
