oss-slu/Mouser

CageSetupFrame.py, ExperimentSetupFrame.py, GroupOrganizationFrame.py, GroupSetupFrame.py, IdSetupFrame.py, NavigateButton.py, main.py
- Main.py: I added the animal setup frame (ExperimentSetupFrame) and removed the back button from said frame.
- All previously made Experiment Setup frames were modified by removing the 'next page' parameter. They instead initialize the next page in a function of the frame's class and navigate to said next page via the Next button. Back buttons are also functional leading to the previous page in the sequence. 
- ExperimentSetupFrame.py: fixed leftover camel case variables. 
- CageSetupFrame.py: created cage setup frame
- main.py did not yet have the experiment setup series added, now user can navigate through the experiment setup pages from the homepage of our app. Back button was placed on the Experiment Setup frame instead in order to keep …
=> experiment setup pages navigatable & added CageSetup prototype

accounts.py, main.py, tk_models.py
Closes #20
In our template for the application's pages, I added the option to include navigation buttons, which are shown as "next" and "previous".
These buttons were added so that it is easier for us to move between each of the pages of our application.
In the file where we have all of our templated code (tk_models.py), I added buttons in our template page, where developers are given the option to add the navigation buttons if they want, but they aren't required to.
Screenshots:
This shows what the "next" button looks like in the raw version of our page template.
This is where the user goes when clicking on the "next" button from the first page. If you click on the "previous" button here, it leads you back to that …
=> Previous and Next Buttons

experiment_pages/experiment.py, experiment_pages/group_config_ui.py, experiment_pages/select_experiment_ui.py, experiment_pages/summary_ui.py
experiment.py was modified to store the date experiment was created (this still needs to be passed to the database).
experiment_selection was modified to initialize the NewExperimentUI object on "create" button press rather than ExperimentsUI initialization in order to have a new object made upon a second/new create experiment creation sequence.
- this was necessary as before changes the user's input did not reset after finishing one experiment creation and then beginning to create a second experiment file. The experiment would then be overwriting the previous data in the database as well rather than creating a new entry.
summary_ui,py was modified to call the ExperimentsUI to update the frame. 
- when this object is connected to the database, we will pull all experiments and the page …
=> Small Fixes to Experiment Setup

main.py, tk_models.py
**What was Changed?**
The app's root window was modified to allow resizing with the restraint of the minimum size being equal to the default window size given.
Tk_models was given functions to resize both the Canvas that serves as the backdrop of the application window as well as the title banner that appears atop each page.
**Why was this Changed?**
The app was not previously able to be resized at all or allowed to be made full-screen. This resize functionality will help better the user experience of the app as well as allow pages to display more necessary information at a time.
**Next Steps:**
Some individual pages will need to be modified to better display information and reflect this change.
**Screenshots:**
Before:
After:
=> Main Window of App Resizable

experiment_pages/cage_config_ui.py, experiment_pages/group_config_ui.py, experiment_pages/new_experiment_ui.py, experiment_pages/select_experiment_ui.py, experiment_pages/summary_ui.py, scrollable_frame.py, tk_models.py
**What Was Changed**
Horizontal scroll capability was added to the scroll frame class. 
The class name VerticalScrolledFrame was changed to ScrolledFrame to reflect these changes.
The page and scrollbars now extend to encompass a larger/smaller area when the main window is resized.
The pages using the scroll object were modified to use the new name.
Some extraneous code was removed from VerticalScrolledFrame and its size was changed to reflect window resize.
**Why Was This Changed**
The static sizing of the app window did not allow the optimum user experience when viewing some pages of the app that had the potential to expand greater than the size of the window. 
The cage configuration page was dependent on this capability to be able to comfortably display more/all cages at once.
=> Horzontal scroll/resize

experiment_pages/experiment.py, experiment_pages/group_config_ui.py, experiment_pages/new_experiment_ui.py
- experiment class & new_experiment_ui was modified to keep track of changes in user input to the number of groups and measurement items.
- group_config_ui was modified to only destroy group name text boxes and radio buttons if there was a change in user input to the above upon entering and exiting of pages.
- A clarifying label was added above the measurement item radio buttons on group_config_ui 
**Why was this changed?**
- changes were based on client feedback 
- A bug was detected on the group name configuration page in the create new experiment sequence. Previously if the user exited the page the text boxes were destroyed and recreated upon reentry to account for dynamic changes in the number of text boxes populated, however this resulted in the user's input …
=> New group name entry bug fix & add "Input Method" label

database_controller.py, experiment_pages/cage_config_ui.py, experiment_pages/experiment_menu_ui.py
**What Was Changed?**
Current state of animals/cages/groups in Group Configuration UI page saves to the database upon click of 'Save' button. 
- Animal Ids re-order numerically based on what cage they are moved to based on client's request and are saved to the database in that fashion. (i.e. Cage 1 always houses Animal 1 and so forth)
**Known Bugs:**
There is not currently a place within the UI application that puts animals/animal ids into cages and saves to the database, based on the call written for saving to the database there needs to be a value present to update. Because our test experiments in the application do not have this feature, the call does not work properly when using the UI alone. 
- Testing outside the UI found that the calls made work as expected, however the current …
=> Cage Configuration Save to Database

experiment_pages/cage_config_ui.py
Change cage group configuration to display vertically, to horizontally.
Fixes #110
Change cage group configuration to display vertically, to horizontally. Only had to rewrite one line of code, placing the side of the frame as left instead of top.
Was an issue listed, also much easier to read without required scrolling for multiple cage groups.
Simply rewrote the frame.pack() line to display side to side instead of top to bottom.
**Screenshots that show the changes (if applicable):**
=> Cage Group Display Horizontal

experiment_pages/map_rfid.py, requirements.txt, serial_port_controller.py, test.py
Fixes #114 
Map RFID file has been changed so that there's an option to access to a new GUI serial Port that allow user to select which serial port they want to use for the experiment. 
The changes were made because there's no function to select a serial port to transfer data previously. 
The changes were made by creating a new button on the Map RFID GUI that access a serial port GUI containing table of the name of available ports provided by the pc as well as the description of those ports. Users can select the GUI they want to use by selecting the name of the serial port directly and then hit Select Port button at the bottom. However, the button doesn't do anything currently as there's limited ways to test the functionality of serial port. …
=> Implement serial port selection for measurement

experiment_pages/experiment_menu_ui.py
Fixes #126 
experiment_pages_ui.py
- delete_experiment()
While delete experiments, would overwrite created_experiments.csv would create extra empty lines in the file. This caused errors when other methods tried to read the file. Changed it so they no longer appear. 
```
open('./database_apis/created_experiments.csv', 'w')
```
is now
```
open('./database_apis/created_experiments.csv', 'w', newline="")
```
Overrides the default newline character with an empty string so that it doesn't create empty lines.
Added a return line so that when there is an OS error in the delete_experiment method it doesn't continue delete the entry in created_experiments.csv
=> 126 experiment deletion error

experiment_pages/map_rfid.py, serial_port_controller.py
Fixes #113
Improvement are made to the original serial port selection panel that allow it to choose the serial port to get the rfid from.
Originally, the panel was set up so to allow the Mouser application to have the ability to connect to other device via serial port. However, the actual implementation of connection hasn't been set up yet, so it currently resides in the map_rfid page. The changes made from this branch now allows this functionality to select a serial port from the available serial ports to read and obtain the rfid for the animals.
The changes were implemented by creating a serial port controller in the map_rfid page and connect the functionality of the controller to read from the serial port to the original function that add the rfid to the animal label. The selection of …
=> implementation of method that allow serial port to sent rfid

main.py
Removes the login page from the main frame, automatically displays the accounts/ experiments option. In future, will automatically go to experiments page when accounts are removed.
Fixes #139 
The login frames that were instructed to be raised when the main would run was removed and replaced with the main_frame which asks users for either accounts or experiments.
The login screen/ opening frame.
Was unnecessary for our clients use.
Just redirects the main to run without the login page.
Slight change of code and removal of login frames on main.
=> Update Opening Frame

database_apis/data_collection_database.py, database_controller.py, experiment_pages/data_collection_ui.py, experiment_pages/experiment_menu_ui.py, experiment_pages/map_rfid.py, experiment_pages/select_experiment_ui.py, main.py
Fixes #140 
Added a menu bar that contains the functionality to open a database file from anywhere on their computer.
The previous code would not be able to handle the user moving the .db file to anywhere other than the previously hard-coded directory.
Menu objects are used to create a drop down menu at the top of the window. This is done in the initialization of the ExperimentUI object. (Lines 31-35 of select_experiment_ui.py)
The funcition *open_file()* asks the user to select a file using their native OS's file chooser. It then instantiates an ExperimentMenuUI object using the given file as the name. (Lines 109-112)
Changed initializers in data_collection_ui.py, database_controller.py, data_colection_database.py, and …
=> Added menu bar that has an option to open a file from any location

database_apis/experiment_database.py, experiment_pages/experiment.py, experiment_pages/new_experiment_ui.py
Fixes #123
A method to add unique id to the experiment has been created. New column added to the experiment table of the database file.
The feature is implemented because a unique id is needed to label the experiment instead of experiment name (there's a warning that avoid duplicated naming convention).
Package uuid is used that can generate random id is used to create the id for the experiment. Each time an experiment is created, there'll be a random id generated by uuid. To record the id, a new column called id is created in the experiment_database.py that's used to record the id.
=> implementing unique id generation for experiment

experiment_pages/experiment_menu_ui.py
Fixes #166 
The delete experiment function was changed such that it now properly deletes the experiment files when the warning window pops up and the user pressed yes.
However, another problem arose with recent version of Mouser is that it won't delete the protected experiment files due to the way protected file is displayed. The protected file seen in Mouser is a new file created in temporary directory of the device, and the path it stores does not point to the actual location of the file but the temporary directory instead.
The delete function is changed because the logic of how we opened the experiment file from the mouse application is changed. Originally the delete function uses the name of the experiment to delete the experiment. …
=> Reimplemented the delete function

experiment_pages/experiment/experiment_menu_ui.py, main.py
Fixes #168 
Nothing was changed currently, but problems were identified. There are two possible errors that could occur when trying to access protected experiment files:
- If the first time the password is incorrect when opening the file, then that means the file path that got passed to the password manager isn't byte, which gives error when trying to read from the file. However, I rarely encounter this error, and the next error is the main problem of this issue, so I put the possible error here in case someone else encounters this problem in the future and needs a reference.
- if the password is incorrect the second time a user tries to access the file after opening it for the first time, then it's the problem of the database of the previous temporary file hasn't …
=> Fixing incorrect password error

experiment_pages/create_experiment/summary_ui.py, main.py, shared/experiment.py, shared/file_utils.py, shared/password_utils.py
Fixes #171 
Changed file creation and opening to use '.pmouser' as a marker of a protected mouser file instead of "_Protected"
Changed file opening such that both protected and unprotected files are opened as temporary files.
Added new option in the file menu called "save" which saves the data from the temp file to the permanent file.
The original configuration would cause errors if someone renamed a file. An unprotected file with "_Protected" in the name would be mistaken as a password protected file while a protected file without "_Protected" would be mistaken as a normal file.
Changed the naming convention of a protected file to have the .pmouser file extension.
Added new file called "file_utils.py" which contains …
=> Changed experiment to name protected files as .pmouser files

main.py, settings/serial ports/.csv, settings/serial ports/preference/serial_port_preference.csv, settings/serial ports/test2.csv, shared/serial_port_settings.py
Fixes #190 
A new file that contains the preferred configuration for serial port setting is added. Functions related to preference configuration is added so that when Mouser application is started the serial port setting is automatically set to the preferred configuration.
Preference configuration is set so that user don't have to manually set the serial port setting every time they open the program.
A file was added to the preference directory in setting/serial ports that will contain the preference configuration for the serial port setting page. Implementation in the class SerialPortSetting is applied such that it checks if there's a file in the preference directory that contains the file name of the preferred …
=> implementing preference setting to serial port setting page

.github/workflows/Pylint.yaml, .github/workflows/create-executable.yml, experiment_pages/experiment/experiment_menu_ui.py
Fixes #219 
GitHub Actions has removed support for its v2, so we have updated to v4.
The create-executable workflow was automatically failing due to this deprecation, and not actually running the workflow.
=> switched actions to v4 from v2

main.py
Fixes #225 
- Got rid of the useless button that originally held the Mouser logo and instead opted to change it to 2 separate image and text labels respectively. 
- Two buttons were added to the home screen, "New Experiment" and "Open Experiment", they simply mirror the usage of the file > "New Experiment"/"Open Experiment".
- Changed the window size to open to the users display dimensions upon startup. 
- Solved the quick issue of the password box not closing when the inputted password is correct.
- Removed the original Mouser logo setup because I believe that (A) it was a useless button so there was no need for it, and (B) The fact that it highlighted when hovered could create confusion for users.
- Added the two buttons on the home screen …
=> Home Page UI Update (Issue #225)

experiment_pages/experiment/map_rfid.py
This file forces the program to open the recently created file after all RFIDs have been mapped. This fixes issue #233.
Fixes #233 
map_rfid.py was changed to allow to go straight from experiment creation, to rfid mapping, to data collection, without having to open or close any files. 
The issue was that if a new experiment was created, the user would have to reopen it after mapping rfids but before being able to utilize the data collection page. 
map_rfid.py now stores relevant information locally, such as the parent experiment menu frame and the local path where the newly created experiment is stored. From there, when the user hits the back to menu button, assuming all rfids have been successfully mapped, it then …
=> Changes to map_rfid.py to Fix Issue #233

databases/experiment_database.py, experiment_pages/experiment/map_rfid.py
Fixes #238 
An additional button has been added to the bottom corner of map_rfid.py to sacrifice animals, removing them entirely from the database. 
This was changed to meet the client's specifications. 
An additional button was added into the init portion of the page from line 102-106. It references a new method, sacrifice_selected_items, which is defined on lines 309-323.
=> Added Sacrifice Button to Map_RFID

experiment_pages/experiment/data_collection_ui.py
Fixes #249 
Data from serial devices can now be input without touching the keyboard at all (with exception to sim mode, but that doesn't matter to lab techs).
Our client doesn't want to have to hit a submit button to input data once it's passed to machine. It is unsafe and innefficient.
Created a method that basically just automates the function of the submit button. Once the data handler receives data, it calls the finish method that the submit button used to call and closes out the entry box.
=> Data input is now Touchless

experiment_pages/create_experiment/new_experiment_ui.py, experiment_pages/experiment/map_rfid.py
Fixes #247 
The raise_warning function was updated to allow warning messages to be dismissed with any key press or mouse click, rather than relying solely on the OK button or the close button.
This change was made to improve efficiency during experiments, enabling researchers to quickly dismiss warnings without needing to use a mouse or precisely click a button. 
Key and mouse event bindings were added to the warning window to trigger dismissal. Additionally, the window was set to grab focus upon opening to ensure the events were captured effectively.
=> Fix completed, errors can be closed on button press or mouse click

shared/serial_port_settings.py
Fixes #187 
A back button was added to the summary page of the Serial Port Settings, but it does not yet work.
This was added as there was no way to return to the main menu from the serial port settings page, one would have to load or open a new experiment.
A button was added into the serial_port_settings.py which allows the user to have more options while working and makes it easier for the user to navigate.
=> Button placed in wanted place, not yet functioning

databases/experiment_database.py, experiment_pages/experiment/experiment_menu_ui.py
Fixes issue raised by Client 
NOTE: At present, this fix only applies to the main Experiment Menu Page. Data collection still needs to be updated. 
The code has been modified to check whether RFIDs are flagged as being used for this experiment to disable the other buttons if needed. It also disables the RFID button in the case where the RFID is flagged as not being used. 
The Experiment Menu page now checks whether the experiment uses RFID and disables buttons accordingly per request from the client. 
The Experiment menu page now checks within its disable buttons if needed method whether RFID is flagged as being used for this experiment. If it is being used, it continues as normal. If it is not being used, it disables …
=> RFID No Longer Mandatory for Experiment Menu Page

experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/test_screen.py, main.py, settings/serial ports/preference/device/preferred_config.txt, settings/serial ports/preference/reader/rfid_config.txt, settings/serial ports/preference/serial_port_preference.csv, settings/serial ports/rfid_reader.csv, settings/serial ports/rfid_reader2.csv, settings/serial ports/test_config.csv, settings/serial ports/test_reader.csv, shared/serial_handler.py, shared/serial_listener.py, shared/serial_port_controller.py, shared/serial_port_settings.py, shared/tk_models.py
Fixes #260 
The application can now handle more than one (two) serial devices at a time. Created a test screen that can detect and test both RFID devices.
In order for our clients to be able to scan mice into the system AND take in measurements, they must be able to use RFID readers and measurement devices at the same time. This is a very important feature to the integrity of the deployment of this program.
Rather than having one preference folder that finds the desired device settings, I split it into "Device" and "RFID" folders and did a bunch of changes to how objects like the serial controller, handler, and listener are instantiated in order to effectively maneuver which device is which. I haven't been able to test …
=> Multiple Device Integration

shared/file_utils.py
Fixes #262
Inside the shared folder, the file utilities have been updated to better reflect the clients needs. Now, whenever the (existing file) is being saved, it is now saved with the experiment name followed by a timestamp in the file name. NOTE: This does not add a timestamp to the experiment upon creation. This functionality could be implemented upon request, but I am operating under the assumption that the creation of the experiment itself does not need a timestamp added to the file. 
This was changed to reflect the needs of the client, who are working in a system that needs both iterative saves and a proper understanding of when all data points were saved. This PR is part of a larger enhancement being worked on currently, the parent of …
=> Changes to Save Function to Add Timestamps 

experiment_pages/experiment/data_collection_ui.py
Fixes #269 
Added a simple if/else clause that triggers the automatic data collection only if the input method flag was set to automatic, and renders a simple submit button if manual.
**This solution assumes the current use case for Mouser in having exclusively 1 measurement device. If multiple measurement devices (not counting RFID reader devices) want to be supported the data collection ui will have to be modified.**
=> Data collection uses input method setting (auto/manual) from experiment creation

experiment_pages/experiment/data_collection_ui.py
Fixes #271 
Added an additional check when opening the experiment (and thus calling the data_collection screen) to create and map pseudo RFIDs to the database to allow data collection without needing RFIDs.
This was change to match client functional needs of not having RFIDs on experiments, but still have full Mouser Functionality.
Inside the data_collection.py file, the experiment now checks if there are animals with RFIDs mapped inside of the database. In the case that there are, the changes are ignored, and the program runs exactly as before. If there are not, however, as will be the case with experiments not utilizing RFID chips, it now creates "fake" RFIDs that just match the animal number. So, if there are 10 …
=> No rfid mapping solution

experiment_pages/experiment/cage_config_ui.py, experiment_pages/experiment/group_config_ui.py
Fixes #248 
The file was updated to include functionality for selecting two animals and swapping their group or cage assignments. This is not yet fully functioning.
The change was made to provide a more interactive and efficient way for users to manage group configurations within experiments. This functionality allows users to directly control animal assignments within the UI, which can be particularly useful in complex experimental setups.
Implementing involved adding selection mechanisms next to each animal's display and a Swap button to initiate the swap. The swap button is not yet functioning.
=> first changes to improve group mapping

experiment_pages/experiment/map_rfid.py
Fixes #279 
Finalized RFID mapping page to continuously accept RFID readings as well as error handling duplicate RFID scans.
There is no reason for our client to continuously hit a button to scan in a specimen. This significantly cleans up the process of mapping in specimens.
I modified rfid_map.py with similar features as the data collection overhaul that I did for issue #263 . The RFID mapping essentially works like a grocery store checking mechanism. It handles serial inputs both locally in the file as well as the database for security/cleanliness of results.
=> Continuous RFID mapping

experiment_pages/create_experiment/new_experiment_ui.py
Removed warning option 1 and all checks for max animal divisibility. Tested a newly created experiment with 7 animals and 2 cages and all other feat. including data collection, map rfid, and data export are functional.
Max animals were forced to be exactly equal to max animals per cage * number of cages. This does not fit with client lab specifications as sometimes the experiments are run such that not all cages are filled e.g. 2 cages with 7 hamsters).
The screenshot below was ran on the branch from https://github.com/oss-slu/Mouser/pull/286 as group/cage config is not updated on main. 
**Screenshots that show the changes**
=> Max animal divisibility check removed

.github/workflows/create-executable.yml, settings/serial ports/.csv, settings/serial ports/Caliper.csv, settings/serial ports/random.csv, settings/serial ports/rfid_reader.csv, settings/serial ports/rfid_reader2.csv, settings/serial ports/serial_port_preference.csv, settings/serial ports/test1.csv, settings/serial ports/test2.csv, settings/serial ports/test_config.csv, settings/serial ports/test_reader.csv, shared/serial_port_settings.py
Fixes *issue not yet defined, will be*
Device settings could not save in the executable version of Mouser, they now can!
Although we have Dr. Toth's current devices hardcoded to Mouser, this addition will be important if our clients desire a hardware change/ new kind of measurement.
os.getcwd() only works with command line versions of programs, replacing that with conditionals that check whether the program is running from the command line vs executable clears up confusion for the system to find paths.
=> Device settings should save in .exe

experiment_pages/create_experiment/new_experiment_ui.py
Fixes Investigator Adding Issue
The New Experiment page now takes the investigator in the text box without having to hit the + button.
This was changed to have the program better match client needs and requests. 
When saving, the program now checks if there is anything within the investigator text box. If there is, it adds it to the list of investigators.
=> Fixed Investigator Text Box Issue

experiment_pages/create_experiment/new_experiment_ui.py, experiment_pages/experiment/group_config_ui.py
The Enter key can now be pressed to input a researcher name while creating a new experiment.
Commonly used default values added for measurement items, RFID, and data collection settings while creating new experiment.
=> Investigator fix

databases/database_controller.py, databases/experiment_database.py, experiment_pages/create_experiment/summary_ui.py, experiment_pages/experiment/cage_config_ui.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/experiment_menu_ui.py, experiment_pages/experiment/map_rfid.py, main.py
Fixes #292 , #257 , and #232 
The AutoSave function has been implemented into all relevant screens, including the Group Config screen, the Map RFID screen, and the Data Collection Screen. In addition, the bugs related to Map RFID, including when removing selected animals, sacrificing animals, and how the list and database were set up, have been resolved. Now, when an animal is removed/sacrificed, the correct animal ID is assigned to the next scanned/simulated one as needed. In addition, a stop listening button has been added to prevent issues with threading should it be needed. Lastly, a Move Group button has been added to the Group Config screen. This allows for either a one animal to be moved from one group to another, or several to be moved from the same or …
=> AutoSave Functionality Implementation, Map RFID Page Fixes, Move Group Button on Group Config

experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/map_rfid.py
Fixes #307 
A raise_warning function was added to DataCollectionUI, and error situations during RFID scanning and data saving were updated to call this warning popup instead of only printing errors.
It was changed to provide clear, immediate feedback to the user during errors, improving usability and making error handling consistent with other parts of the application like Map RFID.
The change introduced a CTkMessagebox popup alongside playing an error sound whenever an RFID scan failed or saving data failed, ensuring users get a visible and audible alert.
=> first changes in adding error dialogue

databases/experiment_database.py, experiment_pages/create_experiment/new_experiment_ui.py, experiment_pages/experiment/cage_config_ui.py, experiment_pages/experiment/review_ui.py
Fixes #321 
Removed instances of cage being mentioned in the UI for groups
We want a clear division between the two as cages will be used to describe different control groups of animals down the line so it should be reserved for talking about those
Instances that appear on the UI as "Cage" Now state "Group"
**Screenshots that show the changes (if applicable):**
=> change occurences of 'cage' to 'group' for ui components

.github/workflows/create-executable.yml, experiment_pages/create_experiment/new_experiment_ui.py, experiment_pages/experiment/cage_config_ui.py, experiment_pages/experiment/data_analysis_ui.py, experiment_pages/experiment/data_collection_ui.py, experiment_pages/experiment/map_rfid.py, main.py, shared/file_utils.py, shared/serial_port_controller.py, shared/serial_port_settings.py
Fixes #315 
Moved the commonly used get_resource_path method from main to the shared/file.utils so that all files can use this method without circular imports from main
Added global variables SUCCESS and ERROR sound that use get_resource_path so that other files can simply import these variables and the sounds will use the proper file path, even in the .exe 
Wrapped file paths for serial settings with get_resource_path method so that serial setting file paths are understood correctly in the .exe 
All sounds and serial settings tested within the .exe and function properly.
Updated GH Action to only create executable in the appropriate branches
=> Serial settings and sounds work correctly in .exe
